enum Categories {
  None = "",
  Music = "music",
  Building = "building",
  Electronics = "electronics",
  Code = "code",
}

enum Projects {
  Bathhouse = "bathhouse",
  BabyPigFeederV1 = "babypigfeederv1",
  BabyPigFeederV2 = "babypigfeederv2",
  ThreeDPrinting = "ThreeDPrinting",
  BoxTruck = "BoxTruck",
}

type Image = {
  id: number;
  src: string;
  homePage: boolean;
  categories: Categories[];
  poster?: string;
  projects?: Projects[];
};

const Images: Image[] = [
  {
    src: "/video/meetingTheUniverseHalfway.mp4",
    poster: "/img/meetinguniverse.png",
    categories: [Categories.Music],
    homePage: true,
    id: 3,
  },
  {
    src: "/img/boxtruckkitcheninbarnfacingcamera.png",
    homePage: true,
    categories: [Categories.Building],
    id: 0,
  },
  {
    src: "/img/3dprint_croped.gif",
    homePage: true,
    categories: [Categories.Building],
    id: 0,
  },
  {
    src: "/img/boxtruckdoorinstallday.png",
    homePage: true,
    categories: [Categories.Building],
    projects: [Projects.BoxTruck],
    id: 0,
  },
  {
    src: "/img/bathhousecomplete.png",
    homePage: true,
    categories: [Categories.Building],
    projects: [Projects.Bathhouse],
    id: 0,
  },
  {
    src: "/img/babypigfeedermk2deconstructed.png",
    homePage: true,
    categories: [Categories.Electronics],
    id: 0,
  },
  {
    src: "/video/modularOnTheSpotLA.mp4",
    poster: "/img/modularOnTheSpotLA.jpg",
    homePage: true,
    categories: [Categories.Music],
    id: 4,
  },
  {
    src: "/img/boxtruckfinished.png",
    homePage: true,
    categories: [Categories.Building],
    id: 2,
  },
  {
    src: "/img/chickenwater.png",
    homePage: true,
    categories: [Categories.Electronics],
    id: 0,
  },
  {
    src: "/video/anotherScienceIsPossible.mp4",
    poster: "/img/anotherscience.png",
    homePage: true,
    categories: [Categories.Music],
    id: 1,
  },
  {
    src: "/img/boxtrucksolarpanels.png",
    homePage: true,
    categories: [Categories.Building],
    id: 0,
  },
  {
    src: "/img/playinglivelovers.png",
    homePage: true,
    categories: [Categories.Music],
    id: 0,
  },
  {
    src: "/img/boxtruckcabside.png",
    homePage: true,
    categories: [Categories.Building],
    id: 0,
  },
  {
    src: "/img/bathhouseroof.png",
    homePage: true,
    categories: [Categories.Building],
    projects: [Projects.Bathhouse],
    id: 0,
  },
  {
    src: "/img/amcwithjar.png",
    homePage: true,
    categories: [Categories.Electronics],
    id: 2,
  },
  {
    src: "/img/codelibretto.png",
    homePage: true,
    categories: [Categories.Code],
    id: 0,
  },
  {
    src: "/img/babypigfeederv1.png",
    homePage: true,
    categories: [Categories.Electronics],
    projects: [Projects.BabyPigFeederV1],
    id: 0,
  },
  {
    src: "/img/tinyhousefixingwindowoutside03.png",
    homePage: true,
    categories: [Categories.Building],
    id: 0,
  },
  {
    src: "/video/betweenPastAndFuture.mp4",
    poster: "/img/betweenpastAndfuture.png",
    homePage: true,
    categories: [Categories.Music],
    id: 2,
  },
  {
    src: "/img/tinyhousev1.5witplants.png",
    homePage: true,
    categories: [Categories.Building],
    id: 0,
  },
  {
    src: "/img/babypigfeederpower.png",
    homePage: true,
    categories: [Categories.Electronics],
    projects: [Projects.BabyPigFeederV1],
    id: 0,
  },
  {
    src: "/img/boxtruck8020frame.png",
    homePage: true,
    categories: [Categories.Building],
    id: 0,
  },
  {
    src: "/img/woodpilezdistance.png",
    homePage: true,
    categories: [Categories.Building],
    id: 0,
  },
  {
    src: "/img/boxtrucksolarcomplete.png",
    homePage: true,
    categories: [Categories.Building, Categories.Electronics],
    id: 0,
  },
  {
    src: "/img/playinglivemicrokorg.png",
    homePage: true,
    categories: [Categories.Music],
    id: 0,
  },
  {
    src: "/img/outdoortable.png",
    homePage: true,
    categories: [Categories.Building],
    id: 0,
  },
  {
    src: "/img/diyeurorackpowerbefacobreadboard.png",
    homePage: true,
    categories: [Categories.Electronics],
    id: 0,
  },
  {
    src: "/img/boxtruckv1lookingoutattiny.png",
    homePage: true,
    categories: [Categories.Building],
    id: 0,
  },
  {
    src: "/img/soundpedro.png",
    homePage: true,
    categories: [Categories.Music],
    id: 0,
  },
  {
    src: "/img/stoveandplant.png",
    homePage: true,
    categories: [Categories.Building],
    id: 0,
  },
  {
    src: "/img/playinglivesandwichplace.png",
    homePage: true,
    categories: [Categories.Music],
    id: 0,
  },
  {
    src: "/img/shedinprogress02.png",
    homePage: true,
    categories: [Categories.Building],
    id: 0,
  },
  {
    src: "/img/boxtrucksolarshutoffs.png",
    homePage: true,
    categories: [Categories.Building],
    id: 0,
  },
  {
    src: "/img/woodshedinprogress.png",
    homePage: true,
    categories: [Categories.Building],
    id: 0,
  },
  {
    src: "/img/solarmodularcasenobackground.png",
    homePage: true,
    categories: [Categories.Music, Categories.Electronics],
    id: 0,
  },
  {
    src: "/img/tinyhouseairbnbkitchen.png",
    homePage: true,
    categories: [Categories.Building],
    id: 0,
  },
  {
    src: "/img/tinyhouseairbnblookingatfrontdoor.png",
    homePage: false,
    categories: [Categories.Building],
    id: 0,
  },
  {
    src: "/img/tinyhousefizzwatchingfire.png",
    homePage: false,
    categories: [Categories.Building],
    id: 0,
  },
  {
    src: "/img/tinyhousefromdistance.png",
    homePage: false,
    categories: [Categories.Building],
    id: 0,
  },
  // AMC
  {
    src: "/img/amcwithmpc.png",
    homePage: false,
    categories: [Categories.Electronics, Categories.Code],
    id: 7,
  },
  {
    src: "/img/3dprinterstill.png",
    homePage: false,
    categories: [Categories.Building, Categories.Electronics],
    id: 1,
  },
  {
    src: "/img/bathhouseinthewoods.png",
    homePage: false,
    categories: [Categories.Building],
    projects: [Projects.Bathhouse],
    id: 0,
  },
  {
    src: "/img/bathhouselibrary.png",
    homePage: false,
    categories: [Categories.Building],
    projects: [Projects.Bathhouse],
    id: 0,
  },
  {
    src: "/img/bathhouselookingin.png",
    homePage: false,
    projects: [Projects.Bathhouse],
    categories: [Categories.Building],
    id: 0,
  },
  {
    src: "/img/bathhousenoroofyet.png",
    homePage: false,
    categories: [Categories.Building],
    projects: [Projects.Bathhouse],
    id: 0,
  },
  {
    src: "/img/amcwithcode.png",
    homePage: false,
    categories: [Categories.Code, Categories.Electronics],
    id: 1,
  },
  //3D Printing
  {
    src: "/img/3dprintingkrankencart.png",
    homePage: false,
    categories: [Categories.Building],
    projects: [Projects.ThreeDPrinting],
    id: 3,
  },
  // Box Truck
  // Baby Pig Feeder MKI
  {
    src: "/img/babypigfeedermk2lidoff.png",
    homePage: false,
    categories: [Categories.Electronics],
    projects: [Projects.BabyPigFeederV1],
    id: 0,
  },
  {
    src: "/img/babypigfeederplasticfront.png",
    homePage: false,
    categories: [Categories.Electronics],
    projects: [Projects.BabyPigFeederV1],
    id: 0,
  },
  // Baby Pig Feeder MKII
  {
    src: "/img/babypigfeedermk2deconstructed02.png",
    homePage: false,
    categories: [Categories.Electronics],
    projects: [Projects.BabyPigFeederV2],
    id: 0,
  },
  {
    src: "/img/babypigfeedermk2panel.png",
    homePage: false,
    categories: [Categories.Electronics],
    projects: [Projects.BabyPigFeederV2],
    id: 0,
  },
  {
    src: "/img/babypigfeedermk2panelwith3dprinted.png",
    homePage: false,
    categories: [Categories.Electronics],
    projects: [Projects.BabyPigFeederV2],
    id: 0,
  },
  {
    src: "/img/babypigfeederv2.png",
    homePage: false,
    categories: [Categories.Electronics],
    projects: [Projects.BabyPigFeederV2],
    id: 0,
  },
  {
    src: "/img/bluetoothRXbreadboard.png",
    homePage: false,
    categories: [Categories.Electronics],
    id: 0,
  },
  {
    src: "/img/boxtruckACpanel.png",
    homePage: false,
    categories: [Categories.Building],
    id: 0,
  },
  {
    src: "/img/boxtruckbathroomv1.png",
    homePage: false,
    categories: [Categories.Building],
    id: 0,
  },
  {
    src: "/img/boxtruckbatteries.png",
    homePage: false,
    categories: [Categories.Building],
    id: 0,
  },
  {
    src: "/img/boxtruckcampingday.png",
    homePage: false,
    categories: [Categories.Building],
    id: 0,
  },
  {
    src: "/img/boxtruckceiling.png",
    homePage: false,
    categories: [Categories.Building],
    id: 0,
  },
  {
    src: "/img/boxtruckcodingatthegorge.png",
    homePage: false,
    categories: [Categories.Building],
    id: 0,
  },
  {
    src: "/img/boxtruckcounterinprogress.png",
    homePage: false,
    categories: [Categories.Building],
    id: 0,
  },
  {
    src: "/img/boxtruckdoorinstallationatnight.png",
    homePage: false,
    categories: [Categories.Building],
    id: 0,
  },
  {
    src: "/img/boxtruckdrawers.png",
    homePage: false,
    categories: [Categories.Building],
    id: 0,
  },
  {
    src: "/img/boxtruckfromoutsideinprogress.png",
    homePage: false,
    categories: [Categories.Building],
    id: 0,
  },
  {
    src: "/img/boxtruckgorgedistance.png",
    homePage: false,
    categories: [Categories.Building],
    id: 0,
  },
  {
    src: "/img/boxtruckinsulation.png",
    homePage: false,
    categories: [Categories.Building],
    id: 0,
  },
  {
    src: "/img/boxtruckinteriorinprogress.png",
    homePage: false,
    categories: [Categories.Building],
    id: 0,
  },
  {
    src: "/img/boxtruckkitchenframeintruck.png",
    homePage: false,
    categories: [Categories.Building],
    id: 0,
  },
  {
    src: "/img/boxtruckoriginalstateinside.png",
    homePage: false,
    categories: [Categories.Building],
    id: 0,
  },
  {
    src: "/img/boxtruckpancakesday.png",
    homePage: false,
    categories: [Categories.Building],
    id: 0,
  },
  {
    src: "/img/boxtruckpicturewindow.png",
    homePage: false,
    categories: [Categories.Building],
    projects: [Projects.Bathhouse],
    id: 0,
  },
  {
    src: "/img/boxtrucksolarmaterials.png",
    homePage: false,
    categories: [Categories.Building],
    id: 0,
  },
  {
    src: "/img/boxtrucksolarshutdoff.png",
    homePage: false,
    categories: [Categories.Building],
    id: 0,
  },
  {
    src: "/img/boxtrucktyvek01.png",
    homePage: false,
    categories: [Categories.Building],
    projects: [Projects.Bathhouse],
    id: 0,
  },
  {
    src: "/img/boxtruckv1inside.png",
    homePage: false,
    categories: [Categories.Building],
    id: 0,
  },
  {
    src: "/img/boxtruckv1outside.png",
    homePage: false,
    categories: [Categories.Building],
    id: 0,
  },
  {
    src: "/img/diyeurorackpowerbreadboard.png",
    homePage: false,
    categories: [Categories.Electronics],
    id: 0,
  },
  {
    src: "/img/diyeurorackpowerDCbreadboard.png",
    homePage: false,
    categories: [Categories.Electronics],
    id: 0,
  },
  {
    src: "/img/diyeurorackpoweropen.png",
    homePage: false,
    categories: [Categories.Electronics],
    id: 0,
  },
  {
    src: "/img/finishedshed.png",
    homePage: false,
    categories: [Categories.Building],
    id: 0,
  },
  {
    src: "/img/playinglivefantasminablackandwhite.png",
    homePage: false,
    categories: [Categories.Music],
    id: 0,
  },
  {
    src: "/img/playinglivefantasminavocals.png",
    homePage: false,
    categories: [Categories.Music],
    id: 0,
  },
  {
    src: "/img/playinglivemodularonthespot-1.png",
    homePage: false,
    categories: [Categories.Music],
    id: 0,
  },
  {
    src: "/img/playinglivemodularonthespot.png",
    homePage: false,
    categories: [Categories.Music],
    id: 0,
  },
  {
    src: "/img/sheddistance.png",
    homePage: false,
    categories: [Categories.Building],
    id: 0,
  },
  {
    src: "/img/shedinprogress03.png",
    homePage: false,
    categories: [Categories.Building],
    id: 0,
  },
  {
    src: "/img/solarmodularcasezoomedin.png",
    homePage: false,
    categories: [Categories.Music, Categories.Electronics],
    id: 0,
  },
  {
    src: "/img/solarmodularcat.png",
    homePage: false,
    categories: [Categories.Music, Categories.Electronics],
    id: 0,
  },
  {
    src: "/img/tinyhouseairbnbkitchenonly.png",
    homePage: false,
    categories: [Categories.Building],
    id: 0,
  },
  {
    src: "/img/tinyhouseandbathhouse.png",
    homePage: false,
    categories: [Categories.Building],
    projects: [Projects.Bathhouse],
    id: 0,
  },
  {
    src: "/img/tinyhouseempty.png",
    homePage: false,
    categories: [Categories.Building],
    id: 0,
  },
  {
    src: "/img/tinyhousefixingwindowindoors.png",
    homePage: false,
    categories: [Categories.Building],
    id: 0,
  },
  {
    src: "/img/tinyhousefixingwindow.png",
    homePage: false,
    categories: [Categories.Building],
    id: 0,
  },
  {
    src: "/img/tinyhouseguyintree.png",
    homePage: false,
    categories: [Categories.Building],
    id: 0,
  },
  {
    src: "/img/tinyhouseinsidev1.png",
    homePage: false,
    categories: [Categories.Building],
    id: 0,
  },
  {
    src: "/img/tinyhouseinthesnow.png",
    homePage: false,
    categories: [Categories.Building],
    id: 0,
  },
  {
    src: "/img/tinyhouserainbow.png",
    homePage: false,
    categories: [Categories.Building],
    id: 0,
  },
  {
    src: "/img/tinyhousesidinginprogress.png",
    homePage: false,
    categories: [Categories.Building],
    id: 0,
  },
  {
    src: "/img/tinyhousesunset.png",
    homePage: false,
    categories: [Categories.Building],
    id: 0,
  },
  {
    src: "/img/tinyhousev1sided.png",
    homePage: false,
    categories: [Categories.Building],
    id: 0,
  },
  {
    src: "/img/tinyhousev1workingonsink.png",
    homePage: false,
    categories: [Categories.Building],
    id: 0,
  },
  {
    src: "/img/tinyhousewindowfinishedcelebration.png",
    homePage: false,
    categories: [Categories.Building],
    id: 0,
  },
  {
    src: "/img/woodpile.png",
    homePage: false,
    categories: [Categories.Building],
    id: 0,
  },
  {
    src: "/img/woodpilesideprofile.png",
    homePage: false,
    categories: [Categories.Building],
    id: 0,
  },
  {
    src: "/img/osccover.png",
    homePage: false,
    categories: [Categories.Building],
    id: 0,
  },
  {
    src: "/img/babypigfeedermk2panel2.png",
    homePage: false,
    categories: [Categories.Electronics],
    id: 0,
  },
  {
    src: "/video/youJoy.mp4",
    poster: "/img/youjoywithcode.png",
    homePage: false,
    categories: [Categories.Music, Categories.Electronics, Categories.Code],
    id: 0,
  },
  {
    src: "/video/youJoy.mp4",
    poster: "/img/youjoywithcode.png",
    homePage: false,
    categories: [Categories.Music, Categories.Electronics, Categories.Code],
    id: 0,
  },
];

export { Images, Categories, Projects };
